import type { Metadata } from "next";

import "./globals.css";
import Providers from "./providers";
import CustomDock from "./components/CustomDock";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` font-grey-reg antialiased`}
      >
        <Providers><CustomDock orientation={"vertical"} />
       {children}</Providers> 
      </body>
    </html>
  );
}
